#!/bin/bash

export GITHUB_TOKEN=AAAAAAAAAA



#myArray=("taimen" "blueline" "sargo")
#myArray=("sailfish" "walleye")
myArray=("walleye")
for str in ${myArray[@]}; do
  echo $str
github-release release --user BBBBBBBBBB --repo dilbech --tag walleye
#rm -fr download.lineage.microg.org
#wget --no-verbose -r -l1 --no-parent https://download.lineage.microg.org/$str
#cd download.lineage.microg.org/$str
wget --no-verbose https://mirrorbits.lineageos.org/full/walleye/20221025/lineage-19.1-20221025-nightly-walleye-signed.zip
for i in `ls line*`
do
echo $i
github-release upload --user BBBBBBBBBB \
   --repo dilbech \
   --tag $str  \
   --name  $i --file  $i
sleep 10
done

done

exit 0
